version: "2"
sql:
  - engine: "postgresql"
    schema: "../app/externals/database/sql/schema.sql"
    queries: "../app/externals/database/sql/queries.sql"
    gen:
      go:
        package: "db"
        out: "../app/externals/database/sqlc"
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
