package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
)

// IsEmailAvailable is the resolver for the isEmailAvailable field.
func (r *queryResolver) IsEmailAvailable(ctx context.Context, email string) (bool, error) {
	return r.Resolver.SignUpService.IsEmailAvailable(ctx, email)
}
